// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLEntryMVC.Data;

#nullable disable

namespace URLEntryMVC.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230125133535_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("URLEntryMVC.Entities.UrlTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlLink")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UrlTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
